### ISSUE TITLE
KeyError: 'module name can\'t contain "."'

### ISSUE THREAD

**Issue by MollyHoo** [yingcong/Facelet_Bank#17]
Traceback (most recent call last):
  File "test_facelet_net.py", line 110, in <module>
    Framework.run()
  File "D:\xinghu\Facelet_Bank\util\framework.py", line 32, in run
    self.func_dict[args.command]()
  File "test_facelet_net.py", line 81, in test_video
    decoder = vgg_decoder()
  File "D:\xinghu\Facelet_Bank\network\decoder.py", line 16, in __init__
    self._define_model()
  File "D:\xinghu\Facelet_Bank\network\decoder.py", line 25, in _define_model
    self.model = base_network.Vgg_recon()
  File "D:\xinghu\Facelet_Bank\network\base_network.py", line 141, in __init__
    self.recon5 = _PoolingBlock(3, 512, 512, drop_rate=drop_rate)
  File "D:\xinghu\Facelet_Bank\network\base_network.py", line 189, in __init__
    padding=1))
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 196, in add_module
    raise KeyError("module name can't contain \".\"")
KeyError: 'module name can\'t contain "."'

**Comment by MollyHoo** [comment]
打印了name出现conv.1，楼主是什么愿意呀

**Comment by yingcong** [comment]
要用pytorch 0.3.1，太新了不兼容

**Comment by MollyHoo** [comment]
作者有没有win10版本的呀，win10上没有0.3.1版本的
