### ISSUE TITLE
Training and preparing the dataset

### ISSUE THREAD

**Issue by AidasK** [yingcong/Facelet_Bank#5]
Hi, I am trying to train my own model, but I am getting this error:
```
Traceback (most recent call last):
  File "train_facelet_net.py", line 68, in <module>
    train()
  File "train_facelet_net.py", line 54, in train
    for idx, data in enumerate(tqdm(dataloader), 0):
  File "/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.py", line 930, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/aidas/quiz-facebank/data/trainDataset.py", line 62, in __getitem__
    npz[0] = torch.cat((npz[0], cur_npz[: 256 * scale1 * scale1].view(256, scale1, scale1)), 0)
RuntimeError: invalid argument 2: size '[256 x 112 x 112]' is invalid for input with 1277952 elements at /pytorch/torch/lib/TH/THStorage.c:41
```

My assumption is that I should not be using celeba "Align&Cropped Images"  dataset, because all images in it are of size "178x218". Maybe I should use "In-The-Wild Images" and crop them to 448x448 myself? 

Readme contains this note: "Note: In our implementation, we use the aligned version of celebA dataset for training, and resize the images to 448 x 448." Does this mean, that before making "attribute_vectors" I should resize and crop all the images to 448 x 448? Or train_facelet_net.py should handle it by itself? 
If I have to crop and resize all the images to 448 x 448 should all of them be aligned in the same way? (e.g. all eyes and noses should be in the same spot) 

Thanks for any help!

**Comment by yingcong** [comment]
Hi @AidasK , the train_facelet_net.py does not resize the image. So you need to resize them manually before running train_facelet_net.py. Face alignment is not strictly needed because the DFI code already incorporates it.
